---
title: "Numerical Analysis"
output: html_notebook
---
```{r}
library(foreign) 
library(lavaan)
library(semPlot)
library(tikzDevice)
library(semTools)

hz <- read.csv('CFA_num.csv', header = TRUE)

hz <- subset(hz, select = -c(X))

hz <- hz %>%
  rename(
    Item1 = X10,
    Item2 = X12,
    Item3 = X17,
    Item4 = X18,
    Item5 = X20,
    Item6 = X3,
    Item7 = X6,
    Item8 = X7,
  )

hz.model <- '
Output =~ Item1 + Item2 + Item3 + Item4 + Item5
MandU =~ Item6 + Item7 + Item8'


hz.fit <- cfa(hz.model, data=hz, test = "satorra.bentler")
summary(hz.fit, standardized=TRUE)

semPlot::semPaths(hz.fit)

p <- semPaths(hz.fit, whatLabels="est",
              sizeMan = 3.25,
              node.width = 1,
              edge.label.cex = .75,
              style = "ram",
              mar = c(10, 5, 10, 5))

indicator_order  <- c("Item1", "Item2",
                      "Item3", "Item4", "Item5",
                      "Item6", "Item7", "Item8")

indicator_factor <- c( "MnU", "MnU", "MnU", "MnU",
                       "MnU", "Otp", "Otp", "Otp")



fitmeasures(hz.fit, c('cfi', 'rmsea', 'rmsea.ci.upper', 'bic', 'tli', 'srmr'))

```
```{r}
fitmeasures(hz.fit, c('cfi', 'rmsea', 'rmsea.ci.upper', 'bic', 'tli', 'srmr'))
```



```{r}

jpeg(file="numerical_CFA.jpeg")
plot(p)
dev.off()
```

```{r}
# File path for the PNG
png("Num_CFA.png", width = 6, height = 4, units = "in", res = 300)

# Plot the SEM object
plot(p)

# Close the device
dev.off()
```


```{r}
#Get final factor metrics
inspect(hz.fit, "cor.lv")   # latent variable correlations

# McDonald's Omega for each factor
compRelSEM(hz.fit)


AVE(hz.fit)

```
```{r}
item_item_correlations <- round(cor(hz[, c("Item1", "Item2", "Item3", "Item4",
                      "Item5", "Item6", "Item7",
                      "Item8")]), 2)
```

