---
title: "Categorical Analysis"
output: html_notebook
---

```{r}
library(foreign) 
library(lavaan)
library(semPlot)
library(tikzDevice)
library(tidyverse)
library(semptools)
library(semTools)
```



```{r}
hz <- read.csv('CFA_cat.csv', header = TRUE)
```


```{r}
hz <- subset(hz, select = -c(X))
```

```{r}
hz <- hz %>% 
  rename(
    Item1 = X10,
    Item2 = X11,
    Item3 = X12,
    Item4 = X13,
    Item5 = X16,
    Item6 = X18,
    Item7 = X3,
    Item8 = X6,
    Item9 = X7
    )
```


```{r}
hz.model <- '
MandU =~ Item1 + Item2 + Item3 + Item4 + Item5 + Item6
Output =~ Item7 + Item8 + Item9'
```
```{r}
hz.fit <- cfa(hz.model, data=hz, test = "satorra.bentler")
summary(hz.fit, standardized=TRUE)
```

```{r}
semPlot::semPaths(hz.fit)
```


```{r}
p <- semPaths(hz.fit, whatLabels="est",
        sizeMan = 3.25,
        node.width = 1,
        edge.label.cex = .75,
        style = "ram",
        mar = c(10, 5, 10, 5))

indicator_order  <- c("Item1", "Item2", "Item3", "Item4",
                      "Item5", "Item6", "Item7",
                      "Item8", "Item9")

indicator_factor <- c( "MnU", "MnU", "MnU", "MnU",
                       "MnU", "MnU", "Otp", "Otp", "Otp")

p2 <- set_cfa_layout(p,
                     indicator_order,
                     indicator_factor,
                     fcov_curve = 1.75,
                     loading_position = .8)
plot(p2, fletype = 'tex')


```

```{r}
fitmeasures(hz.fit, c('cfi', 'rmsea', 'rmsea.ci.upper', 'bic', 'tli', 'srmr'))
```

```{r}
# File path for the PNG
png("Cat_CFA.png", width = 6, height = 4, units = "in", res = 300)

# Plot the SEM object
plot(p2)

# Close the device
dev.off()
```



```{r}
#Get final factor metrics
inspect(hz.fit, "cor.lv")   # latent variable correlations

# McDonald's Omega for each factor
compRelSEM(hz.fit)


AVE(hz.fit)

```
```{r}
item_item_correlations <- round(cor(hz[, c("Item1", "Item2", "Item3", "Item4",
                      "Item5", "Item6", "Item7",
                      "Item8", "Item9")]), 2)
```

