---
title: "EFA Numerical"
output: html_notebook
---

First load data and remove empty first column
```{r}
library(foreign) 
library(lavaan)
library(semPlot)
library(tikzDevice)
library(semTools)
library(performance)
library(psych)
library(tidyverse)
library(multilevel)

hz <- read.csv('EFA_num.csv', header = TRUE)

hz <- subset(hz, select = -c(X))
```

Examine factorability of data

```{r}
correlation <- cor(hz)
print(KMO(correlation))

bart.test <- cortest.bartlett(correlation, n = nrow(hz))
print(bart.test)
```

Check Initial Correlation

```{r}
#Get Inter-item Correlations
cor(hz)

#Get item-total Correlations

psych::alpha(hz)
```

Conduct initial EFA

```{r}
efa <- fa(hz, nfactors = 3, fm = "ml", rotate = "promax")
print(efa)

eigen.values <- eigen(correlation) #Inspect Eigen values
eigen.values$values

scree(hz, pc = FALSE) #Inspect Scree Plot
```
Run the final EFA
```{r}
#Rename the Items we're retaining

hz <- hz %>%
  rename(
    Item1 = X10,
    Item2 = X12,
    Item3 = X17,
    Item4 = X18,
    Item5 = X20,
    Item6 = X3,
    Item7 = X6,
    Item8 = X7,
  )


#Run EFA
efa <- fa(hz[, c("Item1" , "Item2" , "Item3" , "Item4" , "Item5" , "Item6" , "Item7" , "Item8")], nfactors = 2, fm = "ml", rotate = "promax")

#Print Results
print(efa)
print(efa$communalities)
print(mean(efa$communalities))
print(efa$loadings)
alpha_f1 <- psych::alpha(hz[, c("Item1" , "Item2" , "Item3" , "Item4" , "Item5" , "Item6" , "Item7" , "Item8")])

# View corrected item–total correlations
alpha_f1$item.stats

```
Get the inter-item correlations
```{r}
#Get Inter-item Correlations
print(min(cor(hz[, c("Item1" , "Item2" , "Item3" , "Item4" , "Item5" , "Item6" , "Item7" , "Item8")])))
print(mean(cor(hz[, c("Item1" , "Item2" , "Item3" , "Item4" , "Item5" , "Item6" , "Item7" , "Item8")])))
cor(hz[, c("Item1" , "Item2" , "Item3" , "Item4" , "Item5" , "Item6" , "Item7" , "Item8")])
```
Compute McDonald's Omega

```{r}
# Now compute omega
omega_result <- omega(hz[, c("Item1" , "Item2" , "Item3" , "Item4" , "Item5" , "Item6" , "Item7" , "Item8")], nfactors = 2)

print(omega_result)
```

And compute the factor-correlations
```{r}
efa$Phi
```

