---
title: "Categorical Analysis"
output: html_notebook
---

```{r}
library(foreign) 
library(lavaan)
library(semPlot)
library(tikzDevice)
library(tidyverse)
library(semptools)
library(semTools)
```



```{r}
hz <- read.csv('CFA_cat.csv', header = TRUE)
```


```{r}
hz <- subset(hz, select = -c(X))

#Check for Mulitvariate Normality
mvn(hz, mvn_test = 'mardia')
#Multivariate Normality is violated so we use robust estimator
```

```{r}
hz <- hz %>% 
  rename(
    Item1 = X10,
    Item2 = X11,
    Item3 = X12,
    Item4 = X13,
    Item5 = X16,
    Item6 = X18,
    Item7 = X3,
    Item8 = X6,
    Item9 = X7
    )
```



```{r}
hz.model <- '
MandU =~ Item1 + Item2 + Item3 + Item4 + Item5 + Item6
Output =~ Item7 + Item8 + Item9'

# hz.model <- '
# MandU =~ Item1 + Item2 + Item3 + Item4 + Item5 + Item6 + Item7 + Item8 + Item9'

hz.fit <- cfa(hz.model, data=hz, estimator = 'wlsmv', ordered = names(hz))
summary(hz.fit, standardized=TRUE)

# 1. Open the PNG device
png("CFA_CAT_FIN.png", width = 10, height = 7, units = "in", res = 300)

# 2. Generate the plot
semPaths(hz.fit, 
         whatLabels = "std",        # Standardized coefficients
         layout = "tree",           # Tree structure
         rotation = 1,              # 1 = Latents at Top, Items at Bottom
         nCharNodes = 0,            # Don't abbreviate variable names
         edge.label.cex = 0.9,      # Size of the loading numbers
         
         # Line Styling
         edge.color = "black",      # Solid black lines
         lty = 1,                   # Force all lines to be solid (no dashes)
         edge.width = 1.2,
         
         # Node Styling
         color = "white",           # White background for boxes/circles
         border.width = 1.5,        # Crisp borders
         sizeMan = 8,               # Width of item boxes
         sizeLat = 12,              # Width of factor circles
         
         # Cleaning the boxes (removes the "weird lines")
         residuals = FALSE,         # Removes error variance arrows/lines
         intercepts = FALSE,        # Removes intercept triangles/lines
         thresholds = FALSE,        # Removes categorical threshold lines
         
         # Layout adjustments
         mar = c(8, 4, 8, 4),       # Margins (Bottom, Left, Top, Right)
         ask = FALSE)

# 3. Save the file
dev.off()

```


```{r}
fitmeasures(hz.fit, c('cfi', 'rmsea', 'rmsea.ci.upper', 'bic', 'tli', 'srmr'))
```



```{r}
#Get final factor metrics
inspect(hz.fit, "cor.lv")   # latent variable correlations

# McDonald's Omega for each factor
compRelSEM(hz.fit)


AVE(hz.fit)

```
```{r}
polychoric(hz[, c("Item1", "Item2", "Item3", "Item4",
                      "Item5", "Item6", "Item7",
                      "Item8", "Item9")])$rho
```

